# Render deployment configuration for ELCA Mothership AIs LIVE DEMO
services:
  # Live Demo Service - 8 Interactive Stations
  - type: web
    name: elca-mothership-api
    env: python
    plan: starter
    buildCommand: |
      pip install fastapi uvicorn websockets python-dotenv openai anthropic pydantic
    startCommand: python elca_live_demo.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: ELCA_COMPLIANCE_MODE
        value: true
      - key: ELCA_BIAS_AUDIT_ENABLED
        value: true
      - key: ELCA_TRANSPARENCY_MODE
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: DEMO_MODE
        value: true
    autoDeploy: true
    branch: main
