apiVersion: v1
kind: Namespace
metadata:
  name: mothership-ais
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership-api
  namespace: mothership-ais
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mothership-api
  template:
    metadata:
      labels:
        app: mothership-api
    spec:
      containers:
      - name: mothership-api
        image: mothership-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: openai-api-key
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: claude-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mothership-api-service
  namespace: mothership-ais
spec:
  selector:
    app: mothership-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mothership-ingress
  namespace: mothership-ais
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: mothership.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mothership-api-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mothership-api-hpa
  namespace: mothership-ais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mothership-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
