apiVersion: v1
kind: Namespace
metadata:
  name: mothership-ais
---
apiVersion: v1
kind: Secret
metadata:
  name: mothership-secrets
  namespace: mothership-ais
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL21vdGhlcnNoaXA6bW90aGVyc2hpcF9wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL21vdGhlcnNoaXA=
  redis-url: cmVkaXM6Ly9yZWRpczozNjc5
  openai-api-key: c2stZXhhbXBsZQ==
  claude-api-key: c2stZXhhbXBsZQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership-api
  namespace: mothership-ais
  labels:
    app: mothership-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mothership-api
  template:
    metadata:
      labels:
        app: mothership-api
    spec:
      containers:
      - name: mothership-api
        image: mothership-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: openai-api-key
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mothership-secrets
              key: claude-api-key
        - name: ENVIRONMENT
          value: "production"
        - name: METRICS_PORT
          value: "8001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mothership-api-service
  namespace: mothership-ais
  labels:
    app: mothership-api
spec:
  selector:
    app: mothership-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership-frontend
  namespace: mothership-ais
  labels:
    app: mothership-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mothership-frontend
  template:
    metadata:
      labels:
        app: mothership-frontend
    spec:
      containers:
      - name: mothership-frontend
        image: mothership-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://mothership-api-service"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://mothership-api-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mothership-frontend-service
  namespace: mothership-ais
  labels:
    app: mothership-frontend
spec:
  selector:
    app: mothership-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mothership-ingress
  namespace: mothership-ais
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: mothership.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mothership-api-service
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: mothership-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mothership-frontend-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mothership-api-hpa
  namespace: mothership-ais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mothership-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mothership-frontend-hpa
  namespace: mothership-ais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mothership-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mothership-api-pdb
  namespace: mothership-ais
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mothership-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mothership-frontend-pdb
  namespace: mothership-ais
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mothership-frontend
