apiVersion: v2
name: mothership-ais
description: Mothership AIs - Central AI with ontological library for specialized agents
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - agents
  - ontology
  - microservices
home: https://github.com/seanebones-lang/Project-Pheonix
sources:
  - https://github.com/seanebones-lang/Project-Pheonix
maintainers:
  - name: Sean McDonnell
    email: sean@mothership-ais.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: rabbitmq
    version: "11.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
