# values.yaml
# Default values for mothership-ais.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: mothership-api
  pullPolicy: IfNotPresent
  tag: "latest"

frontend:
  replicaCount: 2
  image:
    repository: mothership-frontend
    pullPolicy: IfNotPresent
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  metricsPort: 8001

frontendService:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: mothership.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

frontendResources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

frontendAutoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 2

frontendPodDisruptionBudget:
  enabled: true
  minAvailable: 1

# Environment variables
env:
  ENVIRONMENT: "production"
  METRICS_PORT: "8001"

# Secrets
secrets:
  create: true
  databaseUrl: "postgresql://mothership:mothership_password@postgres:5432/mothership"
  redisUrl: "redis://redis:6379"
  openaiApiKey: "sk-example"
  claudeApiKey: "sk-example"

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
    adminPassword: "admin"

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "mothership_password"
    username: "mothership"
    password: "mothership_password"
    database: "mothership"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# RabbitMQ configuration
rabbitmq:
  enabled: true
  auth:
    username: "mothership"
    password: "mothership_password"
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
